name: Create AWS Secret Manager

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      # 3. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Format Check
      - name: Terraform Format
        run: terraform fmt -check

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 8. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
